# To use the OCI Build Service you place a file name ocibuild.conf at the root of your git repo.
# This file, written using the HOCON syntax, will cause a build to automatically be triggered when commits are pushed to your repo.
# The ocibuild.conf file also determines how build service executes the build commands on the source code in your repo.
#
# Build Service Reference: https://confluence.oci.oraclecorp.com/x/7kMZBg
# Where is my build: https://devops.oci.oraclecorp.com/build
# HOCON reference: https://github.com/lightbend/config/blob/master/HOCON.md
# Build Service Slack: #oci_build_svc_users

runnerTag = latest
name: oci-cloud-controller-manager
team: OKE
phoneBookId: oracle-kubernetes-engine
description: oci-cloud-controller-manager build for oke
# CCM release version
majorVersion: 1
# update minorVersion for feature releases
minorVersion: 15
# update patchVersion for bugfixes and small improvements
patchVersion: 1
ccmVersion: v${majorVersion}.${minorVersion}.${patchVersion}
version: ${ccmVersion}

initialBuildNumber = {
"master": 1
"internal": 1
}
releaseBranches: ["master", "internal", "release*"]
triggerOnCommitBranches: ["main", "pull-requests", "master", "internal", "release*"]
authCompartmentOcid: ocid1.compartment.oc1..aaaaaaaaykdfnwdgzksazqom3cujcofsx2o7mrxlrsnsnokp3z6yrijrtgna
pipelineId: ocid1.devopsbuildpipeline.oc1.phx.aaaaaaaa4gcbttfzkdvpxhnqj7j7qom7alv44lto2txra6doz5itye555fyq
bitbucketTag: {"enabled": true, "tagName": ${ccmVersion}-${BLD_NUMBER}, "description": "cloud-provider-oci version "${ccmVersion}-${BLD_NUMBER}}
subProjects: ["release-validator-pop"]

steps:[
    {
      name: gitcheckout
      type: git
      gitCloneType: shallow
      cloneSubmodules: true
      artifacts: [ "**" ]
    },
    {
      name: validate-images-auto-tfvars-json
      type: make
      runnerImage : "build-runner-make-ol8"
      makeCommands: [
        { target: "validate-images-auto-tfvars-json" }
      ]
      dependsOn : gitcheckout
    },
    {
      name: validate-release-validator-pop
      type: make
      runnerImage : "build-runner-make-ol8"
      makeCommands: [
        { target: "validate-release-validator-pop" }
      ]
      dependsOn : gitcheckout
    },
    {
      name: validate-images-auto-tfvars-json-with-default-and-override-values
      type: make
      runnerImage : "build-runner-make-ol8"
      makeCommands: [
        { target: "validate-images-auto-tfvars-json-with-default-and-override-values" }
      ]
      dependsOn : gitcheckout
    }
]
